version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: docker.io/library/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8080:8080"
